### ISSUE TITLE
[FEATURE] 레이아웃 배치

### ISSUE THREAD

**Issue by marshot9420** [marshot9420/marshot-doctrines#1]
### 📄 Describe

블로그의 기본 레이아웃 요소들을 배치

### ✅ Tasks

- [ ] 전역 스타일 설정
- [ ] `Header` 컴포넌트 추가
- [ ] `Footer` 컴포넌트 추가
- [ ] `Sidebar` 컴포넌트 추가
- [ ] 레이아웃 구현

### 🙋🏻 More

반응형으루다가 딱!
