### ISSUE TITLE
[FEATURE] 관리자 페이지 레이아웃

### ISSUE THREAD

**Issue by marshot9420** [marshot9420/marshot-doctrines#3]
### 📄 Describe

관리자 페이지의 기본 레이아웃 추가

### ✅ Tasks

- [x] `TransparentButton` 컴포넌트 추가
- [x] `UserMenu` 컴포넌트 추가
- [x] `AdminHeader` 컴포넌트 추가
- [x] `AdminNavBar` 컴포넌트 추가
- [x] 관리자 페이지 레이아웃 구현
