### ISSUE TITLE
[FEATURE] 관리자 페이지 - 카테고리 추가 기능 구현

### ISSUE THREAD

**Issue by marshot9420** [marshot9420/marshot-doctrines#9]
### 📄 Describe

게시글을 올릴 카테고리를 추가하는 기능 구현

### ✅ Tasks

- [ ] 카테고리 관련 스키마 추가
- [ ] 카테고리 생성 유효성 검증 로직 추가
- [ ] 카테고리 생성 서버 액션 함수 추가
- [ ] `AdminSection` 컴포넌트 추가
- [ ] 이 다음은 뭘 해야 할까

### 🙋🏻 More

**구현 단계**
- 카테고리 카드 컴포넌트 구현
  - 1차, 2차, 3차 카테고리 별로 계층적 구조의 UI 형성
- 카테고리 순서의 위치값을 상태로 관리
- 드래그로 순서 변경 및 계층간 이동 구현
- 저장 버튼 클릭 시 기억된 순서값을 서버 액션으로 전달
